app_name: zero_rails
secret_key_base: TODO
jwt_key: TODO
newrelic_license_key: TODO

database:
  url: postgres://myuser:mypass@localhost/somedatabase

admin:
  user_name: admin
  password: zero-rails-admin
secure_storage:
  default: zero-rails
redis:
  cache_url: redis://localhost:6379/0
  sidekiq_url: redis://localhost:6379/1
